server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
      show-sql: true
      temp.use_jdbc_metadata_defaults: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

  output:
    ansi:
      enabled: ALWAYS


connection-settings:
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
  referrer: http://www.google.com
  timeout: 10000

snippet-settings:
  max-pixel-width: 2000

indexing-settings:
  sites:

    - url: https://www.circusnikulin.ru/
      name: Цирк Никулина

    - url: https://www.skillbox.ru
      name: Skillbox

    - url: https://www.lenta.ru
      name: Лента.ру

    - url: https://www.playback.ru/
      name: PlayBack.Ru

    - url: https://volochek.life/
      name: Жизнь Волочка

    - url: https://ipfran.ru/
      name: Ipfran

    - url: https://dimonvideo.ru/
      name: Видео Димона

    - url: https://nikoartgallery.com/
      name: Art Gallery

#    Ответ на запрос - 400
#    - url: https://et-cetera.ru/mobile/
#      name: Mobile
##
#    - url: https://www.lutherancathedral.ru/
#      name: Cathedral

#    - url: https://dombulgakova.ru/
#      name: Дом булгакова
#      Проблемный (запрещен доступ?)

#    - url: http://radiomv.ru/
#      name: RadioMV
#      Проблемный (запрещен доступ?)

#    - url: https://www.svetlovka.ru/
#      name: Svetlovka
